force-app/main/default/objects/Consignment__c/Consignment__c.object-meta.xml
<CustomObject>
    <description>single shipment of one container</description>
    <label>Consignment</label>
    <nameField>
        <displayFormat>UCC-{00000000}</displayFormat>
        <label>Consignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consignment__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <description>container Number</description>
    <inlineHelpText>container Number</inlineHelpText>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Consignments</relationshipLabel>
    <relationshipName>Consignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consignment__c/fields/Goods__c.field-meta.xml
<CustomField>
    <fullName>Goods__c</fullName>
    <description>name of goods in consignment</description>
    <inlineHelpText>name of goods in consignment</inlineHelpText>
    <label>Goods</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consignment__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <description>number of voyage where consignment is shipping</description>
    <inlineHelpText>number of voyage where consignment is shipping</inlineHelpText>
    <label>Voyage</label>
    <referenceTo>Voyage__c</referenceTo>
    <relationshipLabel>Consignments</relationshipLabel>
    <relationshipName>Consignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consignment__c/fields/Weight_kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_kg__c</fullName>
    <description>weight of parcel in kilograms</description>
    <inlineHelpText>weight of parcel in kilograms</inlineHelpText>
    <label>Weight, kg</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <description>containers managed by United company</description>
    <label>Container</label>
    <nameField>
        <displayFormat>UCMA{0000000}</displayFormat>
        <label>Container Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voyage__c/Voyage__c.object-meta.xml
<CustomObject>
    <description>Shipment of parcel of containers from port to port</description>
    <label>Voyage</label>
    <nameField>
        <displayFormat>UCV-{000000}</displayFormat>
        <label>Voyage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voyages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    
    public static List<Consignment__c> generateConsignmentRecords (List <Container__c> containers, Voyage__c voyage, Integer loops) {

        List<Consignment__c> consignments = new List<Consignment__c>();
        Integer recordsNumber = containers.size() * loops;
        Integer cntrs = containers.size();

        for (Integer i = 0; i < recordsNumber; i++) {
            Integer j = math.mod(i, cntrs);
            consignments.add(new Consignment__c(Container__c = containers.get(j).Id,
                                                Voyage__c = voyage.Id,
                                                Weight_kg__c = 2000,
                                                Goods__c = 'Grain'
                                                ));
        }

        return consignments;

    }


}