force-app/main/default/objects/Consignment__c/Consignment__c.object-meta.xml
<CustomObject>
    <description>single shipment of one container</description>
    <label>Consignment</label>
    <nameField>
        <displayFormat>UCC-{00000000}</displayFormat>
        <label>Consignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consignment__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <description>container Number</description>
    <inlineHelpText>container Number</inlineHelpText>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Consignments</relationshipLabel>
    <relationshipName>Consignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consignment__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <description>number of voyage where consignment is shipping</description>
    <inlineHelpText>number of voyage where consignment is shipping</inlineHelpText>
    <label>Voyage</label>
    <referenceTo>Voyage__c</referenceTo>
    <relationshipLabel>Consignments</relationshipLabel>
    <relationshipName>Consignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <description>containers managed by United company</description>
    <label>Container</label>
    <nameField>
        <displayFormat>UCMA{0000000}</displayFormat>
        <label>Container Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <description>type of sea container</description>
    <inlineHelpText>type of sea container</inlineHelpText>
    <label>Container Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Container_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Max_Payload_kg__c.field-meta.xml
<CustomField>
    <fullName>Max_Payload_kg__c</fullName>
    <description>cargo capacity of container</description>
    <inlineHelpText>cargo capacity of container</inlineHelpText>
    <label>Max Payload, kg</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>After each 5 voyages container needs inspection</description>
    <inlineHelpText>After each 5 voyages container needs inspection</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Need Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Tare_Weight_kg__c.field-meta.xml
<CustomField>
    <fullName>Tare_Weight_kg__c</fullName>
    <description>weight of empty container</description>
    <inlineHelpText>weight of empty container</inlineHelpText>
    <label>Tare Weight, kg</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/Ship__c.object-meta.xml
<CustomObject>
    <description>ship belongs to United company</description>
    <label>Ship</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship__c/fields/Breadth_m__c.field-meta.xml
<CustomField>
    <fullName>Breadth_m__c</fullName>
    <description>Vessel&apos;s Breadth Moulded</description>
    <inlineHelpText>Vessel&apos;s Breadth Moulded</inlineHelpText>
    <label>Breadth, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Capacity_TEU__c.field-meta.xml
<CustomField>
    <fullName>Capacity_TEU__c</fullName>
    <description>Vessel&apos;s capacity in TEU (standard 20-feet container)</description>
    <inlineHelpText>Vessel&apos;s capacity in TEU (standard 20-feet container)</inlineHelpText>
    <label>Capacity, TEU</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Captain__c.field-meta.xml
<CustomField>
    <fullName>Captain__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Captain details</description>
    <inlineHelpText>Captain details</inlineHelpText>
    <label>Captain</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ship&apos;s Captains</relationshipLabel>
    <relationshipName>Ships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Depth_m__c.field-meta.xml
<CustomField>
    <fullName>Depth_m__c</fullName>
    <description>Vessel&apos;s Depth Moulded</description>
    <inlineHelpText>Vessel&apos;s Depth Moulded</inlineHelpText>
    <label>Depth, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Length_m__c.field-meta.xml
<CustomField>
    <fullName>Length_m__c</fullName>
    <description>Vessel maximum length in meters</description>
    <inlineHelpText>Vessel maximum length in meters</inlineHelpText>
    <label>Length, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Unique IMO number of vessel</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique IMO number of vessel</inlineHelpText>
    <label>Serial Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Ship_Class__c.field-meta.xml
<CustomField>
    <fullName>Ship_Class__c</fullName>
    <description>Class of the vessel dependent on her size</description>
    <inlineHelpText>Class of the vessel dependent on her size</inlineHelpText>
    <label>Ship Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Feeder</fullName>
            </value>
            <value>
                <fullName>Feeder</fullName>
            </value>
            <value>
                <fullName>Feedermax</fullName>
            </value>
            <value>
                <fullName>Panamax</fullName>
            </value>
            <value>
                <fullName>Post-Panamax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voyage__c/Voyage__c.object-meta.xml
<CustomObject>
    <description>Shipment of parcel of containers from port to port</description>
    <label>Voyage</label>
    <nameField>
        <displayFormat>UCV-{000000}</displayFormat>
        <label>Voyage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voyages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Voyage__c/fields/Loading_Port__c.field-meta.xml
<CustomField>
    <fullName>Loading_Port__c</fullName>
    <description>port, where the voyage starts</description>
    <inlineHelpText>port, where the voyage starts</inlineHelpText>
    <label>Loading Port</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ports</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voyage__c/fields/Ship__c.field-meta.xml
<CustomField>
    <fullName>Ship__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>name of the vessel performing voyage</description>
    <inlineHelpText>name of the vessel performing voyage</inlineHelpText>
    <label>Ship</label>
    <referenceTo>Ship__c</referenceTo>
    <relationshipLabel>Voyages</relationshipLabel>
    <relationshipName>Voyages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Container_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>20 DV</fullName>
    </customValue>
    <customValue>
        <fullName>40 DV</fullName>
    </customValue>
    <customValue>
        <fullName>40 HC</fullName>
    </customValue>
    <customValue>
        <fullName>45 HC</fullName>
    </customValue>
    <description>list of standard container types</description>
    <masterLabel>Container Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Ports.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Odessa</fullName>
    </customValue>
    <customValue>
        <fullName>Haifa</fullName>
    </customValue>
    <customValue>
        <fullName>Istanbul</fullName>
    </customValue>
    <customValue>
        <fullName>Chittagong</fullName>
    </customValue>
    <customValue>
        <fullName>Xiamen</fullName>
    </customValue>
    <masterLabel>Ports</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConsignmentTriggerHandlerTest.cls
@isTest
public with sharing class ConsignmentTriggerHandlerTest {

    private static final Integer RECORDS_NUMBER = 200;

    @TestSetup
    static void makeData(){

        Contact captain = new Contact(FirstName ='Ivan', 
                                        LastName = 'Petrov', 
                                        Email = 'petrov@email.com'
                                        );

        insert captain;

        Ship__c ship = new Ship__c(Name ='ShipName', 
                                    Serial_Number__c = 'STA-1', 
                                    Ship_Class__c = 'Panamax',
                                    Breadth_m__c = 20,
                                    Capacity_TEU__c = 500,
                                    Depth_m__c = 12,
                                    Length_m__c = 180,
                                    Captain__c = captain.Id
                                    );

        insert ship;

        Voyage__c voyage = new Voyage__c (Loading_Port__c = 'Odessa',
                                            Ship__c = ship.Id
                                    );

        insert voyage;

        Integer length = 20;
        List <Container__c> containers = new List <Container__c>();
        for (Integer i = 0; i < length; i++) {
            containers.add(new Container__c(Color__c = 'RED',
                                            Container_Type__c = '20 DV',
                                            Max_Payload_kg__c = 26000,
                                            Tare_Weight_kg__c = 2300,
                                            Status__c = Constants.CONTAINER_STATUS_ACTIVE
                                           ));
        }

        insert containers;
        
    }

    @isTest
    static void checkConsignmentsInsertTest() {

        Map<Id, Container__c> containers = new Map <Id, Container__c> ([SELECT Id FROM Container__c]);
        Voyage__c voyage = [SELECT Id FROM Voyage__c];
        Integer numberOfLoops = Constants.INSPECTION_LOOP + 4;

        List<Consignment__c> consignments = TestDataFactory.generateConsignmentRecords(containers.values(), voyage, numberOfLoops);
     
        Test.startTest();
        List<Database.SaveResult> results = Database.insert(consignments, false);
        List <ProcessInstance> pInstances = [SELECT TargetObjectId, 
                                                    CreatedDate 
                                                    FROM ProcessInstance 
                                                    WHERE TargetObjectId 
                                                    IN :containers.keySet()
                                                    ];
        Test.stopTest();

        Integer success = 0;
        Integer errors = 0;
        String error;

        for (Database.SaveResult result: results) {
            if (result.isSuccess()) {
                success++;
            }
            if (result.getErrors().size() > 0) {
                if (error == null) {
                    error = result.getErrors()[0].getMessage();
                }
                errors++;
            }

        }

        Integer expectedSuccess = containers.size() * Constants.INSPECTION_LOOP;
        Integer expectedErrors = consignments.size() - expectedSuccess;

        System.assertEquals(containers.size(), pInstances.size());
        System.assertEquals(errors, expectedErrors);
        System.assertEquals(success, expectedSuccess);
        System.assertEquals(Constants.CONSIGNMENT_ADD_ERROR_MESSAGE, error);

    }

}