force-app/main/default/objects/Ship__c/Ship__c.object-meta.xml
<CustomObject>
    <description>ship belongs to United company</description>
    <label>Ship</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship__c/fields/Breadth_m__c.field-meta.xml
<CustomField>
    <fullName>Breadth_m__c</fullName>
    <description>Vessel&apos;s Breadth Moulded</description>
    <inlineHelpText>Vessel&apos;s Breadth Moulded</inlineHelpText>
    <label>Breadth, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Capacity_TEU__c.field-meta.xml
<CustomField>
    <fullName>Capacity_TEU__c</fullName>
    <description>Vessel&apos;s capacity in TEU (standard 20-feet container)</description>
    <inlineHelpText>Vessel&apos;s capacity in TEU (standard 20-feet container)</inlineHelpText>
    <label>Capacity, TEU</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Captain__c.field-meta.xml
<CustomField>
    <fullName>Captain__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Captain details</description>
    <inlineHelpText>Captain details</inlineHelpText>
    <label>Captain</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ship&apos;s Captains</relationshipLabel>
    <relationshipName>Ships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Depth_m__c.field-meta.xml
<CustomField>
    <fullName>Depth_m__c</fullName>
    <description>Vessel&apos;s Depth Moulded</description>
    <inlineHelpText>Vessel&apos;s Depth Moulded</inlineHelpText>
    <label>Depth, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Length_m__c.field-meta.xml
<CustomField>
    <fullName>Length_m__c</fullName>
    <description>Vessel maximum length in meters</description>
    <inlineHelpText>Vessel maximum length in meters</inlineHelpText>
    <label>Length, m</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Unique IMO number of vessel</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique IMO number of vessel</inlineHelpText>
    <label>Serial Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Ship_Class__c.field-meta.xml
<CustomField>
    <fullName>Ship_Class__c</fullName>
    <description>Class of the vessel dependent on her size</description>
    <inlineHelpText>Class of the vessel dependent on her size</inlineHelpText>
    <label>Ship Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Feeder</fullName>
            </value>
            <value>
                <fullName>Feeder</fullName>
            </value>
            <value>
                <fullName>Feedermax</fullName>
            </value>
            <value>
                <fullName>Panamax</fullName>
            </value>
            <value>
                <fullName>Post-Panamax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship__c/fields/Ship_Details__c.field-meta.xml
<CustomField>
    <fullName>Ship_Details__c</fullName>
    <label>Ship Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ShipTriggerHandlerTest.cls
@isTest
public with sharing class ShipTriggerHandlerTest {

    private static final Integer RECORDS_NUMBER = 6;

    @TestSetup
    static void makeData(){
  
        List<Contact> captains = new List<Contact>();
        for (Integer i = 0; i < RECORDS_NUMBER; i++) {
            captains.add(new Contact(FirstName ='FirstName' + i, 
                                        LastName = 'LastName' + i, 
                                        Email = 'con'+ i + '@email.com'
                                        ));
        }
        insert captains;

        List<Ship__c> ships = new List<Ship__c>();
        Integer middle = RECORDS_NUMBER / 2;
        for (Integer i = 0; i < RECORDS_NUMBER; i++) {
            String shipDetails = i > middle ? 'Some details': '';
            ships.add(new Ship__c(Name ='ShipName' + i, 
                                Serial_Number__c = 'STA-' + i, 
                                Ship_Class__c = 'Panamax',
                                Breadth_m__c = i,
                                Capacity_TEU__c = i,
                                Depth_m__c = i,
                                Length_m__c = i,
                                Captain__c = captains.get(i).Id,
                                Contract_Start_Date__c = date.newinstance(2020, 1, 1),
                                Contract_Due_Date__c = Date.today(),
                                Ship_Details__c = shipDetails
                                ));
               
        }
        insert ships;
        
    }

    @isTest
    static void checkPreventClassChangeTest() {

        List<Ship__c> ships = [SELECT Id, Ship_Class__c FROM Ship__c];

        for (Ship__c ship : ships) {
            ship.Ship_Class__c = 'Feeder';
        }
     
        Test.startTest();
        List<Database.SaveResult> results = Database.update(ships, false);
        Test.stopTest();

        boolean isSuccess = false;
        Integer errors = 0;

        for (Database.SaveResult result: results) {
            if (result.isSuccess()) {
                isSuccess = true;
            }
            if (result.getErrors().size() > 0) {
                errors++;
            }

        }

        System.assert(!isSuccess);
        System.assertEquals(errors, RECORDS_NUMBER);
        System.assertEquals(Constants.SHIP_CLASS_CHANGE_ERROR_MESSAGE,
                             results.get(0).getErrors()[0].getMessage());

    }

    @isTest
    static void checkChangeContractDueDateTest() {

        List<Ship__c> ships = [SELECT Id, Name FROM Ship__c];

        for (Integer i = 0; i < RECORDS_NUMBER; i++) {
            ships.get(i).Contract_Due_Date__c = Date.today().addDays(10);
        }
     
        Test.startTest();
        List<Database.SaveResult> results = Database.update(ships, false);
        Test.stopTest();

        boolean isSuccess = true;

        for (Database.SaveResult result: results) {
            if (result.isSuccess() == false) {
                isSuccess = false;
                break;
            }
        }

        System.assert(isSuccess);
        System.assertEquals(results.size(), RECORDS_NUMBER);

    }

    @isTest
    static void addRowToShipDetailsTest() {

        List<Ship__c> ships = [SELECT Serial_Number__c, Name, Ship_Details__c FROM Ship__c];

        boolean isIncluded = true;

        for (Ship__c ship : ships) {
            String row = ship.Serial_Number__c + ' ' + ship.name;
            if (!ship.Ship_Details__c.contains(row)) {
                isIncluded = false;
                break;
            }

        }

        System.assert(isIncluded);

    }

    @isTest
    static void checkChangeCaptainAndSendEmailTest() {
        //Checking only few records due to limitation on mass mail sending in dev org
        Integer recordsLimit = 3;
        List<Ship__c> ships = [SELECT Id, Name FROM Ship__c LIMIT :recordsLimit];
        List<Contact> captains = [SELECT Id FROM Contact LIMIT :recordsLimit];

        for (Integer i = 0; i < recordsLimit; i++) {
            Integer j = (i < recordsLimit - 1)? i + 1 : 0;
            ships.get(i).Captain__c = captains.get(j).Id; 
        }

        Test.startTest();
        List<Database.SaveResult> results = Database.update(ships, false);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();

        boolean isSuccess = true;

        for (Database.SaveResult result: results) {
            if (result.isSuccess() == false) {
                isSuccess = false;
                break;
            }
        }

        System.assert(isSuccess);
        System.assertEquals(results.size(), recordsLimit);
        System.assertEquals(1, invocations, 'An email should be sent');

    }

}